# -*- coding: utf-8 -*-
"""khushboo.project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bx-ys62_DOGZBfiv2YhQ9JCMLOKWaCUc

# **Import Libraries**
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""# **Import Dataset**"""

df = "data/EduPro Online Platform.xlsx"
users = pd.read_excel(df, sheet_name='Users')
courses = pd.read_excel(df, sheet_name='Courses')
transactions = pd.read_excel(df, sheet_name='Transactions')

users.head()

users.tail()

users.shape

users.info()

"""# **Data Cleaning**"""

# checking for duplication

users.nunique()

# missing data values in the form of %

users.isnull().sum()*100/len(users)*100

dup_users = users.duplicated().any()
print("Duplicate Data:", dup_users)

users.describe(include='all')

for col in users.describe(include='object').columns:
  print(col)
  print(users[col].unique())
  print('-'*50)

users.isnull()

sns.heatmap(users.isnull())

users.describe()

ax = sns.countplot(x='Gender',data=users)

for bars in ax.containers:
    ax.bar_label(bars)

"""Data Integration (Joining Sheets)"""

df = transactions.merge(users, on='UserID').merge(courses, on='CourseID')

"""Demographic Segmentation (Age Bands)"""

bins = [0, 18, 25, 35, 45, 100]
labels = ['<18', '18-25', '26-35', '36-45', '45+']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)

"""KPI Calculations"""

total_enrollments = len(df)
avg_age = users['Age'].mean()
gender_dist = users['Gender'].value_counts(normalize=True) * 100

print(f"Total Enrollments: {total_enrollments}")
print(f"Gender Participation: \n{gender_dist}")

"""Visualizations"""

plt.figure(figsize=(10, 6))

"""Age-wise Enrollment"""

sns.countplot(data=df, x='AgeGroup', palette='viridis')
plt.title('Enrollments by Age Group')
plt.show()

"""Category Popularity"""

cat_order = df['CourseCategory'].value_counts().index
sns.countplot(data=df, y='CourseCategory', order=cat_order)
plt.title('Most Popular Course Categories')
plt.show()
